// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TIMAN.Api;

namespace TIMAN.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211022163352_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TIMAN.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Giày nam"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Giày nữ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thời trang nam"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thời trang nữ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thời trang bé yêu"
                        });
                });

            modelBuilder.Entity("TIMAN.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThumbnailImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 10, 22, 23, 33, 51, 790, DateTimeKind.Local).AddTicks(7122),
                            Name = "Giày Sandal Lưới Phối Da Nam XH01",
                            Price = 578000m,
                            ThumbnailImage = "https://timan.vn/Thumb.ashx?s=650&file=/UploadImages/shops/giay-nam/XH01/giay-sandal-luoi-phoi-da-nam-XH01-1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 10, 22, 23, 33, 51, 791, DateTimeKind.Local).AddTicks(4501),
                            Name = "Giày Thể Thao Da Nữ SZ04",
                            Price = 390000m,
                            ThumbnailImage = "https://timan.vn/Thumb.ashx?s=650&file=/UploadImages/shops/giay-nu/SZ04/giay-the-thao-da-nu-SZ04-1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 10, 22, 23, 33, 51, 791, DateTimeKind.Local).AddTicks(4540),
                            Name = "Áo Blazer Nam Hàn Quốc Màu Đen",
                            Price = 289000m,
                            ThumbnailImage = "https://cf.shopee.vn/file/562ca3c692126d72060fab9582481c7f"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DateCreated = new DateTime(2021, 10, 22, 23, 33, 51, 791, DateTimeKind.Local).AddTicks(4558),
                            Name = "Đầm yếm kẻ sọc ca rô",
                            Price = 554900m,
                            ThumbnailImage = "https://cf.shopee.vn/file/1ef91962b386461ee0dd99273142772b"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            DateCreated = new DateTime(2021, 10, 22, 23, 33, 51, 791, DateTimeKind.Local).AddTicks(4626),
                            Name = "Bộ quần áo thu đông trẻ em 7-17kg (1-5 tuổi) ",
                            Price = 39000m,
                            ThumbnailImage = "https://cf.shopee.vn/file/986dfccc518fbfd7ab7b72f070b51939"
                        });
                });

            modelBuilder.Entity("TIMAN.Model.Product", b =>
                {
                    b.HasOne("TIMAN.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
